version: "3"
volumes:
     mysql-data:
       external: true    
services:
    app:
       build: .
       links:
         - db
       ports:
         - "5000:5000"
    db:
       image: mysql:latest
       ports:
         - "3307:3306"
       volumes:
         - mysql-data:/var/lib/mysql
       environment:
         MYSQL_ROOT_PASSWORD: aldebaran




